"""tinytexts table

Revision ID: 02d57dc028be
Revises: 
Create Date: 2021-01-17 23:11:21.248849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d57dc028be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiny_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=768), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiny_text_created'), 'tiny_text', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tiny_text_created'), table_name='tiny_text')
    op.drop_table('tiny_text')
    # ### end Alembic commands ###
