"""tinytext voting

Revision ID: 3b8fb366953e
Revises: 02d57dc028be
Create Date: 2021-01-18 14:02:00.524770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8fb366953e'
down_revision = '02d57dc028be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiny_text', sa.Column('voting_closed', sa.Boolean(), nullable=True))
    op.add_column('tiny_text', sa.Column('voting_closed_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tiny_text_voting_closed_timestamp'), 'tiny_text', ['voting_closed_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tiny_text_voting_closed_timestamp'), table_name='tiny_text')
    op.drop_column('tiny_text', 'voting_closed_timestamp')
    op.drop_column('tiny_text', 'voting_closed')
    # ### end Alembic commands ###
