"""empty message

Revision ID: 42178a31bb6b
Revises: 6ab1e0a57398
Create Date: 2021-01-24 16:58:07.427165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42178a31bb6b'
down_revision = '6ab1e0a57398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deadline')
    # ### end Alembic commands ###
